/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MetricsIndexRouteImport } from './routes/metrics.index'
import { Route as DashboardsSlugIndexRouteImport } from './routes/dashboards.$slug.index'
import { Route as DashboardsSlugEditRouteImport } from './routes/dashboards.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetricsRoute,
} as any)
const DashboardsSlugIndexRoute = DashboardsSlugIndexRouteImport.update({
  id: '/dashboards/$slug/',
  path: '/dashboards/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsSlugEditRoute = DashboardsSlugEditRouteImport.update({
  id: '/dashboards/$slug/edit',
  path: '/dashboards/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/metrics/': typeof MetricsIndexRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug/': typeof DashboardsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/metrics': typeof MetricsIndexRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug': typeof DashboardsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/metrics': typeof MetricsRouteWithChildren
  '/metrics/': typeof MetricsIndexRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug/': typeof DashboardsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors'
    | '/metrics'
    | '/metrics/'
    | '/dashboards/$slug/edit'
    | '/dashboards/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connectors'
    | '/metrics'
    | '/dashboards/$slug/edit'
    | '/dashboards/$slug'
  id:
    | '__root__'
    | '/'
    | '/connectors'
    | '/metrics'
    | '/metrics/'
    | '/dashboards/$slug/edit'
    | '/dashboards/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRoute: typeof ConnectorsRoute
  MetricsRoute: typeof MetricsRouteWithChildren
  DashboardsSlugEditRoute: typeof DashboardsSlugEditRoute
  DashboardsSlugIndexRoute: typeof DashboardsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/dashboards/$slug/': {
      id: '/dashboards/$slug/'
      path: '/dashboards/$slug'
      fullPath: '/dashboards/$slug/'
      preLoaderRoute: typeof DashboardsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$slug/edit': {
      id: '/dashboards/$slug/edit'
      path: '/dashboards/$slug/edit'
      fullPath: '/dashboards/$slug/edit'
      preLoaderRoute: typeof DashboardsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MetricsRouteChildren {
  MetricsIndexRoute: typeof MetricsIndexRoute
}

const MetricsRouteChildren: MetricsRouteChildren = {
  MetricsIndexRoute: MetricsIndexRoute,
}

const MetricsRouteWithChildren =
  MetricsRoute._addFileChildren(MetricsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRoute: ConnectorsRoute,
  MetricsRoute: MetricsRouteWithChildren,
  DashboardsSlugEditRoute: DashboardsSlugEditRoute,
  DashboardsSlugIndexRoute: DashboardsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
