/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as FpaRouteImport } from './routes/fpa'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as FpaIndexRouteImport } from './routes/fpa.index'
import { Route as FpaBoardRouteImport } from './routes/fpa.board'
import { Route as FpaBudgetRouteImport } from './routes/fpa.budget'
import { Route as FpaCashflowRouteImport } from './routes/fpa.cashflow'
import { Route as FpaForecastRouteImport } from './routes/fpa.forecast'
import { Route as FpaReportsRouteImport } from './routes/fpa.reports'
import { Route as FpaScenariosRouteImport } from './routes/fpa.scenarios'
import { Route as FpaSensitivityRouteImport } from './routes/fpa.sensitivity'
import { Route as FpaStatementsRouteImport } from './routes/fpa.statements'
import { Route as FpaUnitEconomicsRouteImport } from './routes/fpa.unit-economics'
import { Route as FpaVarianceRouteImport } from './routes/fpa.variance'
import { Route as FpaWorkforceRouteImport } from './routes/fpa.workforce'
import { Route as MetricsIndexRouteImport } from './routes/metrics.index'
import { Route as MetricsKeyRouteImport } from './routes/metrics.$key'
import { Route as MetricsNewRouteImport } from './routes/metrics.new'
import { Route as DashboardsSlugIndexRouteImport } from './routes/dashboards.$slug.index'
import { Route as DashboardsSlugEditRouteImport } from './routes/dashboards.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const FpaRoute = FpaRouteImport.update({
  id: '/fpa',
  path: '/fpa',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const FpaIndexRoute = FpaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FpaRoute,
} as any)
const FpaBoardRoute = FpaBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => FpaRoute,
} as any)
const FpaBudgetRoute = FpaBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => FpaRoute,
} as any)
const FpaCashflowRoute = FpaCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => FpaRoute,
} as any)
const FpaForecastRoute = FpaForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => FpaRoute,
} as any)
const FpaReportsRoute = FpaReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FpaRoute,
} as any)
const FpaScenariosRoute = FpaScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => FpaRoute,
} as any)
const FpaSensitivityRoute = FpaSensitivityRouteImport.update({
  id: '/sensitivity',
  path: '/sensitivity',
  getParentRoute: () => FpaRoute,
} as any)
const FpaStatementsRoute = FpaStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => FpaRoute,
} as any)
const FpaUnitEconomicsRoute = FpaUnitEconomicsRouteImport.update({
  id: '/unit-economics',
  path: '/unit-economics',
  getParentRoute: () => FpaRoute,
} as any)
const FpaVarianceRoute = FpaVarianceRouteImport.update({
  id: '/variance',
  path: '/variance',
  getParentRoute: () => FpaRoute,
} as any)
const FpaWorkforceRoute = FpaWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => FpaRoute,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetricsRoute,
} as any)
const MetricsKeyRoute = MetricsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => MetricsRoute,
} as any)
const MetricsNewRoute = MetricsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MetricsRoute,
} as any)
const DashboardsSlugIndexRoute = DashboardsSlugIndexRouteImport.update({
  id: '/dashboards/$slug/',
  path: '/dashboards/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsSlugEditRoute = DashboardsSlugEditRouteImport.update({
  id: '/dashboards/$slug/edit',
  path: '/dashboards/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/fpa': typeof FpaRouteWithChildren
  '/metrics': typeof MetricsRouteWithChildren
  '/fpa/board': typeof FpaBoardRoute
  '/fpa/budget': typeof FpaBudgetRoute
  '/fpa/cashflow': typeof FpaCashflowRoute
  '/fpa/forecast': typeof FpaForecastRoute
  '/fpa/reports': typeof FpaReportsRoute
  '/fpa/scenarios': typeof FpaScenariosRoute
  '/fpa/sensitivity': typeof FpaSensitivityRoute
  '/fpa/statements': typeof FpaStatementsRoute
  '/fpa/unit-economics': typeof FpaUnitEconomicsRoute
  '/fpa/variance': typeof FpaVarianceRoute
  '/fpa/workforce': typeof FpaWorkforceRoute
  '/metrics/$key': typeof MetricsKeyRoute
  '/metrics/new': typeof MetricsNewRoute
  '/fpa/': typeof FpaIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug/': typeof DashboardsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/fpa/board': typeof FpaBoardRoute
  '/fpa/budget': typeof FpaBudgetRoute
  '/fpa/cashflow': typeof FpaCashflowRoute
  '/fpa/forecast': typeof FpaForecastRoute
  '/fpa/reports': typeof FpaReportsRoute
  '/fpa/scenarios': typeof FpaScenariosRoute
  '/fpa/sensitivity': typeof FpaSensitivityRoute
  '/fpa/statements': typeof FpaStatementsRoute
  '/fpa/unit-economics': typeof FpaUnitEconomicsRoute
  '/fpa/variance': typeof FpaVarianceRoute
  '/fpa/workforce': typeof FpaWorkforceRoute
  '/metrics/$key': typeof MetricsKeyRoute
  '/metrics/new': typeof MetricsNewRoute
  '/fpa': typeof FpaIndexRoute
  '/metrics': typeof MetricsIndexRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug': typeof DashboardsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/fpa': typeof FpaRouteWithChildren
  '/metrics': typeof MetricsRouteWithChildren
  '/fpa/board': typeof FpaBoardRoute
  '/fpa/budget': typeof FpaBudgetRoute
  '/fpa/cashflow': typeof FpaCashflowRoute
  '/fpa/forecast': typeof FpaForecastRoute
  '/fpa/reports': typeof FpaReportsRoute
  '/fpa/scenarios': typeof FpaScenariosRoute
  '/fpa/sensitivity': typeof FpaSensitivityRoute
  '/fpa/statements': typeof FpaStatementsRoute
  '/fpa/unit-economics': typeof FpaUnitEconomicsRoute
  '/fpa/variance': typeof FpaVarianceRoute
  '/fpa/workforce': typeof FpaWorkforceRoute
  '/metrics/$key': typeof MetricsKeyRoute
  '/metrics/new': typeof MetricsNewRoute
  '/fpa/': typeof FpaIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug/': typeof DashboardsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors'
    | '/fpa'
    | '/metrics'
    | '/fpa/board'
    | '/fpa/budget'
    | '/fpa/cashflow'
    | '/fpa/forecast'
    | '/fpa/reports'
    | '/fpa/scenarios'
    | '/fpa/sensitivity'
    | '/fpa/statements'
    | '/fpa/unit-economics'
    | '/fpa/variance'
    | '/fpa/workforce'
    | '/metrics/$key'
    | '/metrics/new'
    | '/fpa/'
    | '/metrics/'
    | '/dashboards/$slug/edit'
    | '/dashboards/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connectors'
    | '/fpa/board'
    | '/fpa/budget'
    | '/fpa/cashflow'
    | '/fpa/forecast'
    | '/fpa/reports'
    | '/fpa/scenarios'
    | '/fpa/sensitivity'
    | '/fpa/statements'
    | '/fpa/unit-economics'
    | '/fpa/variance'
    | '/fpa/workforce'
    | '/metrics/$key'
    | '/metrics/new'
    | '/fpa'
    | '/metrics'
    | '/dashboards/$slug/edit'
    | '/dashboards/$slug'
  id:
    | '__root__'
    | '/'
    | '/connectors'
    | '/fpa'
    | '/metrics'
    | '/fpa/board'
    | '/fpa/budget'
    | '/fpa/cashflow'
    | '/fpa/forecast'
    | '/fpa/reports'
    | '/fpa/scenarios'
    | '/fpa/sensitivity'
    | '/fpa/statements'
    | '/fpa/unit-economics'
    | '/fpa/variance'
    | '/fpa/workforce'
    | '/metrics/$key'
    | '/metrics/new'
    | '/fpa/'
    | '/metrics/'
    | '/dashboards/$slug/edit'
    | '/dashboards/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRoute: typeof ConnectorsRoute
  FpaRoute: typeof FpaRouteWithChildren
  MetricsRoute: typeof MetricsRouteWithChildren
  DashboardsSlugEditRoute: typeof DashboardsSlugEditRoute
  DashboardsSlugIndexRoute: typeof DashboardsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fpa': {
      id: '/fpa'
      path: '/fpa'
      fullPath: '/fpa'
      preLoaderRoute: typeof FpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fpa/': {
      id: '/fpa/'
      path: '/'
      fullPath: '/fpa/'
      preLoaderRoute: typeof FpaIndexRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/board': {
      id: '/fpa/board'
      path: '/board'
      fullPath: '/fpa/board'
      preLoaderRoute: typeof FpaBoardRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/budget': {
      id: '/fpa/budget'
      path: '/budget'
      fullPath: '/fpa/budget'
      preLoaderRoute: typeof FpaBudgetRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/cashflow': {
      id: '/fpa/cashflow'
      path: '/cashflow'
      fullPath: '/fpa/cashflow'
      preLoaderRoute: typeof FpaCashflowRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/forecast': {
      id: '/fpa/forecast'
      path: '/forecast'
      fullPath: '/fpa/forecast'
      preLoaderRoute: typeof FpaForecastRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/reports': {
      id: '/fpa/reports'
      path: '/reports'
      fullPath: '/fpa/reports'
      preLoaderRoute: typeof FpaReportsRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/scenarios': {
      id: '/fpa/scenarios'
      path: '/scenarios'
      fullPath: '/fpa/scenarios'
      preLoaderRoute: typeof FpaScenariosRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/sensitivity': {
      id: '/fpa/sensitivity'
      path: '/sensitivity'
      fullPath: '/fpa/sensitivity'
      preLoaderRoute: typeof FpaSensitivityRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/statements': {
      id: '/fpa/statements'
      path: '/statements'
      fullPath: '/fpa/statements'
      preLoaderRoute: typeof FpaStatementsRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/unit-economics': {
      id: '/fpa/unit-economics'
      path: '/unit-economics'
      fullPath: '/fpa/unit-economics'
      preLoaderRoute: typeof FpaUnitEconomicsRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/variance': {
      id: '/fpa/variance'
      path: '/variance'
      fullPath: '/fpa/variance'
      preLoaderRoute: typeof FpaVarianceRouteImport
      parentRoute: typeof FpaRoute
    }
    '/fpa/workforce': {
      id: '/fpa/workforce'
      path: '/workforce'
      fullPath: '/fpa/workforce'
      preLoaderRoute: typeof FpaWorkforceRouteImport
      parentRoute: typeof FpaRoute
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/metrics/$key': {
      id: '/metrics/$key'
      path: '/$key'
      fullPath: '/metrics/$key'
      preLoaderRoute: typeof MetricsKeyRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/metrics/new': {
      id: '/metrics/new'
      path: '/new'
      fullPath: '/metrics/new'
      preLoaderRoute: typeof MetricsNewRouteImport
      parentRoute: typeof MetricsRoute
    }
    '/dashboards/$slug/': {
      id: '/dashboards/$slug/'
      path: '/dashboards/$slug'
      fullPath: '/dashboards/$slug/'
      preLoaderRoute: typeof DashboardsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$slug/edit': {
      id: '/dashboards/$slug/edit'
      path: '/dashboards/$slug/edit'
      fullPath: '/dashboards/$slug/edit'
      preLoaderRoute: typeof DashboardsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FpaRouteChildren {
  FpaBoardRoute: typeof FpaBoardRoute
  FpaBudgetRoute: typeof FpaBudgetRoute
  FpaCashflowRoute: typeof FpaCashflowRoute
  FpaForecastRoute: typeof FpaForecastRoute
  FpaReportsRoute: typeof FpaReportsRoute
  FpaScenariosRoute: typeof FpaScenariosRoute
  FpaSensitivityRoute: typeof FpaSensitivityRoute
  FpaStatementsRoute: typeof FpaStatementsRoute
  FpaUnitEconomicsRoute: typeof FpaUnitEconomicsRoute
  FpaVarianceRoute: typeof FpaVarianceRoute
  FpaWorkforceRoute: typeof FpaWorkforceRoute
  FpaIndexRoute: typeof FpaIndexRoute
}

const FpaRouteChildren: FpaRouteChildren = {
  FpaBoardRoute: FpaBoardRoute,
  FpaBudgetRoute: FpaBudgetRoute,
  FpaCashflowRoute: FpaCashflowRoute,
  FpaForecastRoute: FpaForecastRoute,
  FpaReportsRoute: FpaReportsRoute,
  FpaScenariosRoute: FpaScenariosRoute,
  FpaSensitivityRoute: FpaSensitivityRoute,
  FpaStatementsRoute: FpaStatementsRoute,
  FpaUnitEconomicsRoute: FpaUnitEconomicsRoute,
  FpaVarianceRoute: FpaVarianceRoute,
  FpaWorkforceRoute: FpaWorkforceRoute,
  FpaIndexRoute: FpaIndexRoute,
}

const FpaRouteWithChildren = FpaRoute._addFileChildren(FpaRouteChildren)

interface MetricsRouteChildren {
  MetricsKeyRoute: typeof MetricsKeyRoute
  MetricsNewRoute: typeof MetricsNewRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
}

const MetricsRouteChildren: MetricsRouteChildren = {
  MetricsKeyRoute: MetricsKeyRoute,
  MetricsNewRoute: MetricsNewRoute,
  MetricsIndexRoute: MetricsIndexRoute,
}

const MetricsRouteWithChildren =
  MetricsRoute._addFileChildren(MetricsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRoute: ConnectorsRoute,
  FpaRoute: FpaRouteWithChildren,
  MetricsRoute: MetricsRouteWithChildren,
  DashboardsSlugEditRoute: DashboardsSlugEditRoute,
  DashboardsSlugIndexRoute: DashboardsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
