/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as DashboardsSlugIndexRouteImport } from './routes/dashboards.$slug.index'
import { Route as DashboardsSlugEditRouteImport } from './routes/dashboards.$slug.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsSlugIndexRoute = DashboardsSlugIndexRouteImport.update({
  id: '/dashboards/$slug/',
  path: '/dashboards/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsSlugEditRoute = DashboardsSlugEditRouteImport.update({
  id: '/dashboards/$slug/edit',
  path: '/dashboards/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug/': typeof DashboardsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug': typeof DashboardsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/dashboards/$slug/edit': typeof DashboardsSlugEditRoute
  '/dashboards/$slug/': typeof DashboardsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/metrics' | '/dashboards/$slug/edit' | '/dashboards/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/metrics' | '/dashboards/$slug/edit' | '/dashboards/$slug'
  id:
    | '__root__'
    | '/'
    | '/metrics'
    | '/dashboards/$slug/edit'
    | '/dashboards/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetricsRoute: typeof MetricsRoute
  DashboardsSlugEditRoute: typeof DashboardsSlugEditRoute
  DashboardsSlugIndexRoute: typeof DashboardsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$slug/': {
      id: '/dashboards/$slug/'
      path: '/dashboards/$slug'
      fullPath: '/dashboards/$slug/'
      preLoaderRoute: typeof DashboardsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$slug/edit': {
      id: '/dashboards/$slug/edit'
      path: '/dashboards/$slug/edit'
      fullPath: '/dashboards/$slug/edit'
      preLoaderRoute: typeof DashboardsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetricsRoute: MetricsRoute,
  DashboardsSlugEditRoute: DashboardsSlugEditRoute,
  DashboardsSlugIndexRoute: DashboardsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
